export default {
  // baseURL: "https://api.tradingseek.co.nz/",
  baseURL: "https://api.tradingseek.net/",
  // postjobURL: "https://api.tradingseek.net/",
  bussinessURL: "https://api.business.govt.nz/services/v4/nzbn/entities/",
  Ipinfo: "https://ipinfo.io?token=a8a673ea97bd7e",

  end_Point: {
    LOGIN: "login-user",
    SIGNUP: "register/user",
    FORGET: "forgot-password",
    PROFESSION: "get-all-profession",
    PostJob: "create-job",
    EmailVerify: "get-user-by-email",
    UPDATE_PROFILE_IMG: "update-profile-image",
    GETPROFILE_DATA: "auth/me",
    GETJOB_BY_USER: "get-jobs-by-user-id",
    GETJOB_BY_HIRED: "get-hired-jobs-by-user-id",
    UPDATE_STATUS: "update-job-status/",
    DELET_ACCOUNT: "delete-account",
    PASSWORD: "verify-password",
    UPDATE_USERNAME: "update-user",
    RESET_PASSWORD: "verify-and-update-password",
    UPDATE_DESCRIPTION: "update-description",
    ACCOUNT_ACTIVATE: "activate-account",
    CONVERSATION: "conversations",
    SENDER_MESSAGE: "send-message",
    MESSAGES: "conversation",
    VERIFY_EMAIL: "send-verification-mail",
    UPADTE_USERINFO: "update-user-field",
    SEEN_MESSAGE: "seen-conversation",
    LEAD: "get-leads",
    COMPLAINT: "add-complaint",
    UPDATE_PROFESSION: "update-user-profession",
    UPDATE_LOCATION: "update-user-location",
    ADD_CREDENTIAL: "add-credential",
    GET_FAQS: "get-faqs",
    ADD_QUESTION: "add-faq",
    DELET_FAQS: "delete-faq/",
    SAVE_DRAFT: "save-job-as-draft",
    REMOVE_DRAFT: "remove-draft-leads",
    AUTO_QUOT_SETTING: "update-auto-quote-settings",
    PAYMENT_METHOD: "update-user-payment-methods",
    UPDATE_BUSINESS_HOURS: "update-business-hours",
    ASK_QUESTION: "ask-question",
    DELET_CREDENTIAL: "delete-credential-file",
    SEND_MEDIA_MESSAGE: "send-media-message",
    SEND_QUOTE: "send-quote",
    REMOVE_PROFILE_IMAGE: "remove-profile-image",
    CONVERSATION_MSG: "conversation",
  },
};
